apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/part-of: coreruleset
    coreruleset/file: RESPONSE-952-DATA-LEAKAGES-JAVA.conf
    coreruleset/version: 4.3.0
  name: crs-response-952-data-leakages-java
spec:
  secLangRules:
  - actions:
      disruptive:
        disruptiveActionType: pass
      flow:
      - flowActionType: skipAfter
        value: END-RESPONSE-952-DATA-LEAKAGES-JAVA
      non-disruptive:
      - nonDisruptiveActionType: nolog
    conditions:
    - collections:
      - arguments:
        - Content-Encoding
        name: RESPONSE_HEADERS
      operator:
        name: pm
        value: gzip compress deflate br zstd
    metadata:
      id: 952010
      phase: "4"
      tags:
      - OWASP_CRS/DATA-LEAKAGES-JAVA
  - actions:
      disruptive:
        disruptiveActionType: pass
      flow:
      - flowActionType: skipAfter
        value: END-RESPONSE-952-DATA-LEAKAGES-JAVA
      non-disruptive:
      - nonDisruptiveActionType: nolog
    conditions:
    - collections:
      - arguments:
        - DETECTION_PARANOIA_LEVEL
        name: TX
      operator:
        name: lt
        value: "1"
    metadata:
      id: 952011
      phase: "3"
  - actions:
      disruptive:
        disruptiveActionType: pass
      flow:
      - flowActionType: skipAfter
        value: END-RESPONSE-952-DATA-LEAKAGES-JAVA
      non-disruptive:
      - nonDisruptiveActionType: nolog
    conditions:
    - collections:
      - arguments:
        - DETECTION_PARANOIA_LEVEL
        name: TX
      operator:
        name: lt
        value: "1"
    metadata:
      id: 952012
      phase: "4"
  - actions:
      disruptive:
        disruptiveActionType: block
      non-disruptive:
      - nonDisruptiveActionType: capture
      - nonDisruptiveActionType: logdata
        value: 'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}'
      - nonDisruptiveActionType: setvar
        value: TX.outbound_anomaly_score_pl1=+%{tx.error_anomaly_score}
    conditions:
    - operator:
        name: rx
        value: (?i)\b(?:java[\.a-z]+E(?:xception|rror)|(?:org|com)\.[\.a-z]+Exception|Exception
          in thread \"[^\"]*\"|at[\s\x0b]+(?:ja(?:vax?|karta)|org|com))\b
      variables:
      - name: RESPONSE_BODY
    metadata:
      id: 952110
      message: Java Errors
      phase: "4"
      severity: ERROR
      tags:
      - application-multi
      - language-java
      - platform-multi
      - attack-disclosure
      - paranoia-level/1
      - OWASP_CRS/DATA-LEAKAGES-JAVA
      - capec/1000/118/116
  - actions:
      disruptive:
        disruptiveActionType: pass
      flow:
      - flowActionType: skipAfter
        value: END-RESPONSE-952-DATA-LEAKAGES-JAVA
      non-disruptive:
      - nonDisruptiveActionType: nolog
    conditions:
    - collections:
      - arguments:
        - DETECTION_PARANOIA_LEVEL
        name: TX
      operator:
        name: lt
        value: "2"
    metadata:
      id: 952013
      phase: "3"
  - actions:
      disruptive:
        disruptiveActionType: pass
      flow:
      - flowActionType: skipAfter
        value: END-RESPONSE-952-DATA-LEAKAGES-JAVA
      non-disruptive:
      - nonDisruptiveActionType: nolog
    conditions:
    - collections:
      - arguments:
        - DETECTION_PARANOIA_LEVEL
        name: TX
      operator:
        name: lt
        value: "2"
    metadata:
      id: 952014
      phase: "4"
  - actions:
      disruptive:
        disruptiveActionType: pass
      flow:
      - flowActionType: skipAfter
        value: END-RESPONSE-952-DATA-LEAKAGES-JAVA
      non-disruptive:
      - nonDisruptiveActionType: nolog
    conditions:
    - collections:
      - arguments:
        - DETECTION_PARANOIA_LEVEL
        name: TX
      operator:
        name: lt
        value: "3"
    metadata:
      comment: |+
        -= Paranoia Level 2 =- (apply only when tx.detection_paranoia_level is sufficiently high: 2 or higher)

      id: 952015
      phase: "3"
  - actions:
      disruptive:
        disruptiveActionType: pass
      flow:
      - flowActionType: skipAfter
        value: END-RESPONSE-952-DATA-LEAKAGES-JAVA
      non-disruptive:
      - nonDisruptiveActionType: nolog
    conditions:
    - collections:
      - arguments:
        - DETECTION_PARANOIA_LEVEL
        name: TX
      operator:
        name: lt
        value: "3"
    metadata:
      id: 952016
      phase: "4"
  - actions:
      disruptive:
        disruptiveActionType: pass
      flow:
      - flowActionType: skipAfter
        value: END-RESPONSE-952-DATA-LEAKAGES-JAVA
      non-disruptive:
      - nonDisruptiveActionType: nolog
    conditions:
    - collections:
      - arguments:
        - DETECTION_PARANOIA_LEVEL
        name: TX
      operator:
        name: lt
        value: "4"
    metadata:
      comment: |+
        -= Paranoia Level 3 =- (apply only when tx.detection_paranoia_level is sufficiently high: 3 or higher)

      id: 952017
      phase: "3"
  - actions:
      disruptive:
        disruptiveActionType: pass
      flow:
      - flowActionType: skipAfter
        value: END-RESPONSE-952-DATA-LEAKAGES-JAVA
      non-disruptive:
      - nonDisruptiveActionType: nolog
    conditions:
    - collections:
      - arguments:
        - DETECTION_PARANOIA_LEVEL
        name: TX
      operator:
        name: lt
        value: "4"
    metadata:
      id: 952018
      phase: "4"
    secMarker: END-RESPONSE-952-DATA-LEAKAGES-JAVA
