apiVersion: seclang.kubewaf.io/v1beta1
kind: SecAction
metadata:
  labels:
    app.kubernetes.io/name: wafv2
    app.kubernetes.io/managed-by: kustomize
  name: secaction-sample
spec:
  non-disruptive:
  - setenv

