apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/name: wafv2
    app.kubernetes.io/managed-by: kustomize
  name: secrule-sample
spec:
  metadata:
    id: 1000
    message: "Detects SQL injection attacks in the query string"
    phase: "1"
    severity: "CRITICAL"
    tags:
      - sql-injection
  variables:
    - name: "ARGS_COMBINED_SIZE"
  operator:
    name: "beginsWith"
  actions:
    disruptive: drop
    non-disruptive:
      - auditlog
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/name: wafv4
    app.kubernetes.io/managed-by: kustomize
  name: secrule-sample2
spec:
  metadata:
    id: 1000
    message: "Detects SQL injection attacks in the query string"
    phase: "1"
    severity: "CRITICAL"
    tags:
      - sql-injection
  variables:
    - name: "ARGS_COMBINED_SIZE"
  operator:
    name: "beginsWith"
  actions:
    disruptive: drop
    non-disruptive:
      - auditlog
---
apiVersion: seclang.kubewaf.io/v1beta1
kind: SecRule
metadata:
  labels:
    app.kubernetes.io/name: wafv4
    app.kubernetes.io/managed-by: kustomize
  name: secrule-sample3
spec:
  metadata:
    id: 1000
    message: "Detects SQL injection attacks in the query string"
    phase: "1"
    severity: "CRITICAL"
    tags:
      - sql-injection
  variables:
    - name: "ARGS_COMBINED_SIZE"
  operator:
    name: "beginsWith"
  actions:
    disruptive: drop
    non-disruptive:
      - auditlog